pr:
  autoCancel: true
  branches:
    include:
      - main
  drafts: false

trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: github
      name: PackageAware/build-templates
      endpoint: 'PackageAware'
      ref: refs/heads/main

stages:
  - template: npm-pipeline-template-v2.yml@templates
    parameters:
      projectName: $(Build.Repository.Name)
      useStaticFileHandler: true
      usePrivateRegistry: true
