#!/bin/sh

# PROD
#export SOOS_CLIENT_ID=cd7b07ef8e36601c27541b7b532be3a1c091e1108f3713151095bc269c8c2a5e
#export SOOS_API_KEY=YzY4MDA4MTAtYjRhNi00OTQ3LTk1NGMtOWVlY2Q2ZTQyNmFl

# DEV
export SOOS_CLIENT_ID=c4337d37a91c0180875d901c0d8810ea44b1735ac4a00ca6c0afed13ae0ee48a
export SOOS_API_KEY=MDFkNDFlZGEtZTZlNC00YjU0LWIwMGQtYmFhNTMzM2Q5M2U3

SOOS_PROJECT_NAME="SCA Python Integration Test"
# BUILD/BRANCH SPECIFIC ARGS:
SOOS_COMMIT_HASH=""                # ENTER COMMIT HASH HERE IF KNOWN
SOOS_BRANCH_NAME="Gemfile"                # ENTER BRANCH NAME HERE IF KNOWN
SOOS_BRANCH_URI=""                 # ENTER BRANCH URI HERE IF KNOWN
SOOS_BUILD_VERSION=""              # ENTER BUILD VERSION HERE IF KNOWN
SOOS_BUILD_URI=""                  # ENTER BUILD URI HERE IF KNOWN
SOOS_OPERATING_ENVIRONMENT=""      # ENTER OPERATING ENVIRONMENT HERE IF KNOWN (default will be provided)
SOOS_INTEGRATION_NAME="Script"

# OPTIONAL ARGS:
WORKSPACE="./manifests/gemfile" #PUT YOUR REPO PATH HERE
SOOS_MODE="run_and_wait"
SOOS_ON_FAILURE="fail_the_build"
SOOS_DIRS_TO_EXCLUDE="../../../src/cli"
SOOS_FILES_TO_EXCLUDE=""
SOOS_ANALYSIS_RESULT_MAX_WAIT=300
SOOS_ANALYSIS_RESULT_POLLING_INTERVAL=10
SOOS_CHECKOUT_DIR="${PWD}/manifests/gemfile"
SOOS_API_BASE_URL="https://dev-api.soos.io/api/"

cd ${WORKSPACE}

python3 -m venv venv
source venv/bin/activate

pip3 install -r ../../../src/cli/requirements.txt
python3 ../../../src/cli/soos.py -m="${SOOS_MODE}" -of="${SOOS_ON_FAILURE}" -dte="${SOOS_DIRS_TO_EXCLUDE}" -fte="${SOOS_FILES_TO_EXCLUDE}" -wd="${SOOS_CHECKOUT_DIR}" -armw=${SOOS_ANALYSIS_RESULT_MAX_WAIT} -arpi=${SOOS_ANALYSIS_RESULT_POLLING_INTERVAL} -buri="${SOOS_API_BASE_URL}" -scp="${SOOS_CHECKOUT_DIR}" -pn="${SOOS_PROJECT_NAME}" -ch="${SOOS_COMMIT_HASH}" -bn="${SOOS_BRANCH_NAME}" -bruri="${SOOS_BRANCH_URI}" -bldver="${SOOS_BUILD_VERSION}" -blduri="${SOOS_BUILD_URI}" -oe="${SOOS_OPERATING_ENVIRONMENT}" -intn="${SOOS_INTEGRATION_NAME}"
