name: Tests

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - main
      - 'release-*'

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: soos-io/soos-sca-github-action@v1.2.2
      with:
        project_name: ${{ github.repository }}
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Test with unittest
      run: |
        cd tests
        python -m unittest tests.py
      env:
        SOOS_CLIENT_ID: ${{ secrets.SOOS_CLIENT_ID }}
        SOOS_API_KEY: ${{ secrets.SOOS_API_KEY }}
        SOOS_GITHUB_PAT: ${{ secrets.SOOS_GITHUB_PAT }}
