name: Create a Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Tagged Pre Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: shasum python script
        run: shasum -a 256 src/cli/soos.py > src/cli/soos.sha256
      - name: shasum requirements
        run: shasum -a 256 src/cli/requirements.txt > src/cli/requirements.sha256
      - name: shasum VERSION
        run: shasum -a 256 src/cli/VERSION.txt > src/cli/VERSION.sha256
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          files: |
            src/cli/VERSION.txt
            src/cli/VERSION.sha256
            src/cli/requirements.txt
            src/cli/requirements.sha256
            src/cli/soos.py
            src/cli/soos.sha256